name: Golangci-lint


on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"  # Только релизные теги
  pull_request:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: golangci/golangci-lint-action@a4f60bb28d35aeee14e6880718e0c85ff1882e64

      - name: Set up Go
        uses: golangci/golangci-lint-action@v6.0.1 
        with:
          go-version: '1.22'

      - name: Run tests
        run: go test -v ./...

  docker-publish:
    needs: build-test
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')  # только если пушится тег

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/parcel-tracker:${{ github.ref_name }}
            ${{ secrets.DOCKER_USERNAME }}/parcel-tracker:latest
